// greek-mythos-vue/src/components/Dice/Dice.vue
<template>
    <div class="outside-container">
    <span v-if="isMyDice" class="tw-mb-auto tw-mt-s"> Έριξες {{diceResult}}</span>
    <span v-else class="tw-mb-auto tw-mt-s"> Ο χρήστης {{playerName}} έριξε {{diceResult}}</span>
    <div class="dice-container">
        <div id="mpla" >
        </div>
    </div>
</div>
</template>

<script setup>
import rollADie from 'roll-a-die';
import { useAudio } from '@/pages/SinglePlayer/use-audio';
import { onMounted } from 'vue';
const props = defineProps({
    isMyDice: {
        type: Boolean,
    },
    playerName: {
        type: String,
        default: '',
    },
    diceResult: {
        type: Number,
        required: true,
    },
});
const emits = defineEmits(['done']);
const {settings} = useAudio();

onMounted(() => {

    rollADie({
        element: document.getElementById('mpla'), numberOfDice: 1,
        callback: () => {
            console.log('callback from dice: :)')
        },
        noSound: !!settings.value.effectsMute,
        delay: 3000,
        values: [props.diceResult],
        soundVolume: settings.value.effects,
    });
    setTimeout(() => {
        console.log('callback set timeout: :)')
         emits('done');
       }, 3000);
})


</script>

<style scoped>
.dice-container {
  transform: scale(1.5);
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.outside-container {
  height: 500px;

}

span {
  color: #3f99ec;
  line-height: 50px;
}

</style>

// greek-mythos-angular-2/src/app/views/dice/dice.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { objectKVs } from '@app/helpers/object-keys-values';
import { Game } from '@app/models/game';
import { AudioService } from '@app/services/audio.service';
import { AuthService } from '@app/services/auth.service';
// Maybe find a way to import better :P
declare const rollADie: any;
@Component({
  selector: 'app-dice',
  templateUrl: './dice.component.html',
  styleUrls: ['./dice.component.scss'],
})
export class DiceComponent implements OnInit {

  constructor(
    private authService: AuthService,
    private audioService: AudioService,
  ) { }
  @Input() diceResult = 0;
  playerName = '';

  @Input({ required: true } ) game!: Game;

  isMyDice = false;

  @Output() changeSomething = new EventEmitter();

  @Input() noSound = false;
  @Input() isSinglePlayer = false;

  async ngOnInit(): Promise<void> {
    const soundVolume = this.audioService.getEffectsVolume();
    console.log(this.diceResult);
    this.isMyDice = this.game.players[this.authService.appUser!.uid].turnIndex === this.game.turnIndex;
    const players = this.game.players;
    this.playerName = objectKVs(players).find(player => players[player.key]!.turnIndex === this.game.turnIndex)!.value.displayName;
    rollADie({
      element: document.getElementById('mpla'), numberOfDice: 1, callback: () => {}, noSound: this.noSound, delay: 3000, values: [this.diceResult], soundVolume
    });

    setTimeout(() => {
      this.changeSomething.emit();
    }, 3000);


  }

}

<div class="outside-container">
    <span *ngIf="isMyDice" class="mb-auto mt-3"> Έριξες {{diceResult}}</span>
    <span *ngIf="!isMyDice" class="mb-auto mt-3"> Ο χρήστης {{playerName}} έριξε {{diceResult}}</span>
    <div class="dice-container">
        <div id="mpla" >
        </div>
    </div>
</div>
