// greek-mythos-vue/src/pages/SinglePlayer/SinglePlayer.vue
<template>
    <Card v-if="!started" is-large>
        <div class="tw-w-1/2 tw-flex tw-flex-col tw-h-full">
            <h1 class="tw-text-xl tw-text-center tw-mb-n">Το παιχνίδι σου</h1>
            <hr class="tw-w-full tw-mb-n" />
            <SinglePlayerCardSection title="Μέγεθος παιχνιδού">
                <div class="tw-flex tw-items-center tw-p-n tw-pl-0 tw-gap-n">
                    <label class="tw-text-s tw-cursor-pointer" for="small">Μικρό</label>
                    <input class="tw-cursor-pointer" id="small" name="gameType"
                        :checked="options.isSmall" @change="options.isSmall = true"
                        type="radio">
                    <label class="tw-text-s tw-cursor-pointer" for="big">Μεγάλο</label>
                    <input class="tw-cursor-pointer" :checked="!options.isSmall"
                        @change="options.isSmall = false" id="big" name="gameType" type="radio">
                </div>
            </SinglePlayerCardSection>
            <SinglePlayerCardSection title="">
                <Input label="Πόντοι-Στόχος" :value="options.minPoints" :type="'number'"
                    :input-handler="(ev: Event) => options.minPoints = Number((ev.target as HTMLInputElement).value)"
                    :min="50" />
            </SinglePlayerCardSection>

            <SinglePlayerCardSection title="Μέγιστος αριθμός βοηθειών">
                <Input label="Βοήθεια 50/50" :value="options.maxHelps.help_50" :type="'number'"
                    :input-handler="(ev: Event) => options.maxHelps.help_50 = Number((ev.target as HTMLInputElement).value)" />

                <Input class="tw-mt-n" label="Βοήθεια πάσο" :value="options.maxHelps.skip" :type="'number'"
                    :input-handler="(ev: Event) => options.maxHelps.skip = Number((ev.target as HTMLInputElement).value)" />
            </SinglePlayerCardSection>


            <RaisedButton class="tw-mt-n" text="Παίξε" @click.native="startGame(options)" />

        </div>
    </Card>
    <div v-else>
      <PlayersHud :players="board.game.players" :minPoints="board.game.minPoints" :user="userProfile"/>

<div v-if="board && board.game" class="tw-w-full tw-h-full tw-text-xxl tw-text-[#c8c8c8] tw-flex">
    <div class="tw-flex tw-flex-col tw-items-center tw-m-auto tw-min-w-[80%] tw-h-full tw-justify-evenly">
        <div v-for="(row, rowIndex) of board.rows" :key="rowIndex"
            class="tw-h-full tw-my-xs tw-mx-0 tw-flex tw-w-full tw-items-center tw-justify-evenly">
            <div v-for="(cell, cellIndex) of row.cells" :key="cellIndex" class="tw-flex tw-bg-gray-400 tw-m-auto tw-items-center tw-justify-center tw-rounded-s"
                :class="{
                    'tw-h-[100px] tw-w-[100px]': board.game.isSmall,
                    'tw-h-[70px] tw-w-[70px]': !board.game.isSmall
                }">

                <div v-if="gameEventsMap[cell.index] || gameQuestionsMap[cell.index]">
                    <img class="tw-w-[50px] tw-h-[50px] tw-opacity-60" :src="gameEventsMap[cell.index] ? './assets/ex.png' : gameQuestionsMap[cell.index] ? './assets/q.png' : ''"
                        alt="">
                </div>
                <span v-else>{{ cell.index }}</span>

                <div class="tw-flex tw-flex-wrap tw-absolute">
                    <div v-for="p in board.game.players" :key="p.uid" class="tw-z-[100] tw-flex-grow-0 tw-flex-shrink-[40%]">
                        <img v-if="p.position === cell.index" :alt="p.hero!.name"
                            :src="'assets/heroes/' +p.hero!.name + '.png'" class="tw-w-[30px] tw-h-[30px] tw-object-cover">
                    </div>
                </div>
            </div>
        </div>

        <div v-if="canShowDiceAnimation" class="event-container">
            <Dice :dice-result="diceResult" @done="canShowDiceAnimation = false"
            :is-my-dice="isMyDice" :player-name="userProfile!.displayName"/>
            <!-- <app-dice isSinglePlayer :game="board.game" :no-sound="settings.effectsMute"
                :dice-result="diceResult" @changeSomething="canShowDiceAnimation = false">
            </app-dice> -->
        </div>
    </div>
</div>
<div class="turnname-container">
    <span v-if="turnPlayer === userProfile!.displayName">Είναι η σειρά σου</span>
    <span v-if="turnPlayer === 'Υπολογιστής'">Είναι η σειρά του Υπολογιστή</span>
</div>
<div class="dice">
    <button class="tw-w-[70px] tw-h-[70px]" :disabled="!canRoll" @click="rollDice(userProfile!.uid)">
        <i class="tw-w-[70px] tw-h-[70px]">die-icon</i>
    </button>
</div>
<QuestionModal v-if="activeQuestion" :game="board.game " :question="board.game.question"
 :is-my-question="isMyQuestion" :can-do-action="canDoAction" @answer="answerQuestion" @getHelp="getHelp" @getReward="getReward"/>

<app-question-modal v-if="activeQuestion" :game="board.game" :question="board.game.question" :user="userProfile"
    :canDoAction="canDoAction" @getHelpEvent="getHelp($event)" @getRewardEvent="getReward($event)"
    @answeringQuestion="answerQuestion($event)" @qTurnFinished="qTurnFinished()" IS_SINGLE>

</app-question-modal>


<div v-if="gameOverPlayer" class="event-container">
    <h2>  {{gameOverPlayer === 'Υπολογιστής' ? 'Ο Υπολογιστής κέρδισε!' : 'Κέρδισες!'}}</h2>
    <button @click="quitGame()">Έξοδος</button>
</div>

<div v-if="activeGameEvent" class="event-container">
    <div class="tw-text-center tw-mb-s" style="font-size: 14pt;" v-if="!isMyGameEvent">
        Ο {{activeGameEvent.playerUid === 'bot' ? 'Υπολογιστής' : ' χρήστης '+board.game.players[activeGameEvent.playerUid].displayName}} έπεσε σε γεγονός
    </div>
    <h1 class="tw-text-center tw-mt-s">{{!isMyGameEvent ? '"'+activeGameEvent.text+'"' : activeGameEvent.text }}
    </h1>
    <div v-if="isMyGameEvent" class="w-75">
      progress bar {{ fiveSecondTimer }}
        <!-- <mat-progress-bar mode="determinate" [value]="fiveSecondTimer" style="height: 10px;">
        </mat-progress-bar> -->
    </div>
    <!-- <button *ngIf="isMyGameEvent" (click)="answerGameEvent()">Ok</button> -->
</div>

<div class="settings-container">
    <button mat-icon-button class="settings-btn" @click="showSettings = !showSettings"
    :style="{backgroundColor: showSettings ? '#3f99ec' : '#3f99ec80'}">
        <i class="settings-icon">settings2</i>
        <!-- <mat-icon class="settings-icon" svgIcon="settings2"></mat-icon> -->
    </button>
</div>

<div v-if="showSettings" class="event-container">
    <h1 class="text-center mb-auto mt-3">Ρυθμίσεις</h1>

    <div class="d-flex flex-column w-75 mb-auto">
        <!-- MUSIC -->
        <h2 class="text-center">Μουσική</h2>
        <Slider :slider-value="settings.music * 100" @change="turnVolume('music',$event.value)"/>
        <!-- <mat-slider [value]="settings.music * 100" (change)="turnVolume('music',$event.value)"></mat-slider> -->
        <!-- SOUND EFFECTS -->
        <h2 class="text-center">Ηχητικά εφέ</h2>
        <Slider :slider-value="settings.effects * 100" @change="turnVolume('effects',$event.value)"/>
        <!-- <mat-slider [value]="settings.effects * 100" (change)="turnVolume('effects',$event.value)"></mat-slider> -->

        <Checkbox :check-box-value="settings.musicMute" @change="setMute('musicMute', $event.checked)">Σίγαση μουσικής</Checkbox>
        <!-- <mat-checkbox [checked]="settings.musicMute" (change)="setMute('musicMute', $event.checked)">Σίγαση μουσικής
        </mat-checkbox> -->
        <Checkbox :check-box-value="settings.effectsMute" @change="setMute('effectsMute', $event.checked)">Σίγαση
            ηχητικών
            εφέ</Checkbox>
        <!-- <mat-checkbox [checked]="settings.effectsMute" (change)="setMute('effectsMute', $event.checked)">Σίγαση
            ηχητικών
            εφέ</mat-checkbox> -->
    </div>
</div>

    </div>
</template>

<script lang="ts" setup>
import Card from '@/components/common/Card.vue';
import SinglePlayerCardSection from './SinglePlayerCardSection.vue';
import Input from '@/components/Input/Input.vue';
import { computed, ref } from 'vue';
import RaisedButton from '@/components/common/RaisedButton.vue';
import { useSinglePlayer } from './use-single-player';
import { useUserStore } from '@/store/user';
import { storeToRefs } from 'pinia';
import PlayersHud from './PlayersHud.vue';
import { useAudio } from './use-audio';
import Slider from '@/components/common/Slider.vue';
import Checkbox from '@/components/common/Checkbox.vue';
import Dice from '@/components/Dice/Dice.vue';
import QuestionModal from '@/components/QuestionModal/QuestionModal.vue';


const options = ref({
  isSmall: false,
  minPoints: 150,
  maxHelps: {
    help_50: 3,
    skip: 2,
  }
});

const userStore = useUserStore();
const { userProfile } = storeToRefs(userStore);



const {
  started,
  startGame,
  board,
  gameEventsMap,
  gameQuestionsMap,
  canShowDiceAnimation,
  diceResult,
  turnPlayer,
  canRoll,
  rollDice,
  canDoAction,
  getHelp,
  getReward,
  answerQuestion,
  qTurnFinished,
  activeQuestion,
  gameOverPlayer,
  quitGame,
  activeGameEvent,
  isMyGameEvent,
  fiveSecondTimer,
  showSettings,
} = useSinglePlayer();

const {
  settings,
  turnVolume,
  setMute,
} = useAudio();
const isMyDice = computed(() => {
    const myUid = userProfile.value?.uid;
    if (!myUid) {
        throw new Error('Single player you must be logged in');
    }
    return board.value.game.players[myUid].turnIndex === board.value.game.turnIndex;
})
</script>

<style>
.event-container {
    width: 50%;
    position: absolute;
    z-index: 100;
    left: 25%;
    top: 25%;
    display: flex;
    flex-direction: column;
    align-items: center;
    background: #ffffffe8;
    right: 25%;
    bottom: 25%;
    justify-content: center;
    align-items: center;
    border-radius: 5px;
    height: 600px;
}

.turnname-container {
    position: absolute;
    top: 95%;
    left: 50%;
    transform: translate(-50%, -50%);
    background: #d5d5d5bd;
    font-size: 28pt;
    color: #3f99ec;
    height: 50px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    z-index: 100;
}

.dice {
    position: absolute;
    top: 85%;
    left: 5%;
    color: rgb(0, 0, 0);
}

.settings-container {
    position: absolute;
    top: 87%;
    left: 90%;
    color: rgb(0, 0, 0);
}
.settings-icon {
    width: 40px;
    height: 40px;
}

.settings-btn {
    width: 50px;
    height: 50px;
    background: #3f99ec80;
    box-shadow: 0px 0px 4px 2px rgba(0, 0, 0, 0.3);
}
</style>

// greek-mythos-angular/src/app/views/single-player/single-player.component.ts
import { Location } from '@angular/common';
import { Component, EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { takeUntil } from 'rxjs/operators';
import { getNumberFromZeroToX } from 'src/app/helpers/get-number-zero-to-x';
import { halveAnswers } from 'src/app/helpers/half-answers';
import { getSpiralFormOfArray } from 'src/app/helpers/matrix';
import { objectKeys, objectValues } from 'src/app/helpers/object-keys-values';
import { Board } from 'src/app/models/board';
import { Game, GameEvent, GameQuestion } from 'src/app/models/game';
import { Settings } from 'src/app/models/settings';
import { User } from 'src/app/models/user';
import { AudioService } from 'src/app/services/audio.service';
import { AuthService } from 'src/app/services/auth.service';
import { QuestionService } from 'src/app/services/question.service';
import { SinglePlayerService } from 'src/app/services/single-player.service';
import { TimerService } from 'src/app/services/timer.service';
import { EVENTS_MAP_BIG, EVENTS_MAP_SMALL, HELPS, QUESTIONS_MAP_BIG, QUESTIONS_MAP_SMALL } from 'src/environments/environment';

@Component({
  selector: 'app-single-player',
  templateUrl: './single-player.component.html',
  styleUrls: ['./single-player.component.scss']
})
export class SinglePlayerComponent implements OnInit, OnDestroy {

  started = false;

  showSettings = false;

  settings: Settings;

  board: Board;
  gameQuestionsMap: Record<number, true> = {};
  gameEventsMap: Record<number, true> = {};

  newGame = {
    isSmall: false,
    minPoints: 150,
    maxHelps: {
      help_50: 3,
      skip: 2,
    }
  }
  lastStep: number;

  game: Game;

  diffToStepsMap = {
    'easy': 1,
    'medium': 2,
    'hard': 3
  };

  moveInterval = 500;

  canShowDiceAnimation = false;
  diceResult: number;

  canRoll = false;
  canDoAction = false;
  user: User;

  fiveSecondTimer = 100;

  activeQuestion: GameQuestion;
  activeGameEvent: GameEvent;

  isMyQuestion: boolean;
  isMyGameEvent: boolean;

  turnPlayer: string;

  gameOverPlayer: string;

  destroy$ = new EventEmitter();

  constructor(
    private singlePlayerService: SinglePlayerService,
    private audioService: AudioService,
    private questionService: QuestionService,
    private authService: AuthService,
    private timerService: TimerService,
  ) { }

  ngOnInit(): void {
    this.user = this.authService.appUser;

    //load settings
    this.settings = {
      music: Number.parseFloat(localStorage.getItem('music')),
      effects: Number.parseFloat(localStorage.getItem('effects')),
      musicMute: JSON.parse(localStorage.getItem('musicMute')) === true,
      effectsMute: JSON.parse(localStorage.getItem('effectsMute')) === true,
    };
  }

  ngOnDestroy(): void {
    this.audioService.stopBackgroundMusic();
  }

  startGame(): void {
    // and stuff
    this.game = {
      isSmall: this.newGame.isSmall,
      minPoints: this.newGame.minPoints,
      maxHelps: this.newGame.maxHelps,
      createdAt: 0,
      id: '',
      players: this.singlePlayerService.getSinglePlayerPlayers(),
      turnIndex: 0,
      updatedAt: 0,
    };
    this.lastStep = this.game.isSmall ? 49 : 100;
    this.setUpBoard();

    this.canRoll = true;
    this.canDoAction = true;
    this.turnPlayer = this.user.displayName;
    this.started = true;
    this.audioService.playBackgroundMusic();
  }

  setUpBoard(): void {
    this.gameQuestionsMap = {};
    this.gameEventsMap = {};
    this.board = {
      rows: [],
      game: this.game,
    };

    const rows = this.game.isSmall ? 7 : 10;
    const spiralArray = getSpiralFormOfArray(rows);

    for (let i = 0; i < rows; i++) {
      this.board.rows[i] = {
        cells: []
      }
      for (let j = 0; j < spiralArray[i].length; j++) {
        this.board.rows[i].cells[j] = {
          index: spiralArray[i][j],
        };
      }
    }
    if (this.game.isSmall) {
      QUESTIONS_MAP_SMALL.forEach(question => this.gameQuestionsMap[question] = true);
      EVENTS_MAP_SMALL.forEach(gameEvent => this.gameEventsMap[gameEvent] = true);
    } else {
      QUESTIONS_MAP_BIG.forEach(question => this.gameQuestionsMap[question] = true);
      EVENTS_MAP_BIG.forEach(gameEvent => this.gameEventsMap[gameEvent] = true);
    }
  }

  trackById(item) {
    return item.uid;
  }

  turnVolume(type: 'music' | 'effects', volume: number): void {
    console.log(volume);
    const newVolume = volume / 100;
    localStorage.setItem(type, `${newVolume}`);

    // recalculate settings
    this.settings[type] = newVolume;
    this.audioService.stopBackgroundMusic();
    this.audioService.playBackgroundMusic();
  }

  setMute(type: 'musicMute' | 'effectsMute', checked: boolean): void {
    localStorage.setItem(type, JSON.stringify(checked));
    this.settings[type] = checked;
    this.audioService.stopBackgroundMusic();
    this.audioService.playBackgroundMusic();
  }

  async rollDice(uid: string): Promise<void> {
    this.turnPlayer = objectValues(this.board.game.players).find(player => player.turnIndex === this.board.game.turnIndex)?.displayName;
    // roll dicec
    const isBot = uid === 'bot';
    this.canRoll = false;
    const newDiceRoll = getNumberFromZeroToX(6) + 1;

    // show dice animation
    this.diceResult = newDiceRoll;
    this.canShowDiceAnimation = true;
    await new Promise(res => setTimeout(res, 3000));
    this.canShowDiceAnimation = false;

    let mode: 'question' | 'event' | 'gameOver' | 'move' = 'move';
    // is new position event or question
    if (this.gameQuestionsMap[this.board.game.players[uid].position + newDiceRoll]) {
      // its a question
      mode = 'question';
    } else if (this.gameEventsMap[this.game.players[uid].position + newDiceRoll]) {
      // its an event
      mode = 'event';
    } else if (this.board.game.players[uid].position + newDiceRoll >= this.lastStep) {
      // game over or not enought points
      mode = 'gameOver';
    }
    // otherwise just move
    this.board.game.players[uid].oldPosition = this.board.game.players[uid].position;
    this.changeTurn();
    await this.singlePlayerService.handleRoll(this.board.game, newDiceRoll, mode, uid);

    if (this.board.game.gameOver) {
      // game is over
      this.gameOverPlayer = this.board.game.players[objectKeys(this.board.game.gameOver)[0]].displayName;
      console.log(this.board.game);

      return;
    }

    this.activeGameEvent = this.board.game.gameEvent;
    this.activeQuestion = this.board.game.question;
    this.isMyQuestion = this.board.game.question?.playerUid === uid;
    this.isMyGameEvent = this.board.game.gameEvent?.playerUid === uid;

    if (!this.activeGameEvent && !this.activeQuestion) {
      // play with bot
      if (isBot) {
        this.canRoll = true;
      } else {
        await new Promise(res => setTimeout(res, 2000));
        this.rollDice('bot');
        return;
      }
    }

    if (this.activeGameEvent) {
      // start a timeout
      this.timerService.getFiveSecondTimer().pipe(takeUntil(this.destroy$))
        .subscribe(v => {
          if (v === -999) {
            this.removeFiveSecondTimer();
            this.destroy$.emit();
            return;
          }
          const rel = ((100 * v) / 50);
          this.fiveSecondTimer = rel;

        });
    }

    if (this.activeQuestion && uid === 'bot') {
      await this.answerQuestionForBot();
    }

    this.turnPlayer = objectValues(this.board.game.players).find(player => player.turnIndex === this.board.game.turnIndex)?.displayName;
  }

  async answerQuestionForBot(): Promise<void> {
    await this.singlePlayerService.waitFor(3000);
    // answer random
    const _randomNumber = getNumberFromZeroToX(4);
    this.activeQuestion.question.answer = this.activeQuestion.question.answers[_randomNumber];

    // get correct
    const correct = await this.questionService.getAnswerForQuestion(this.activeQuestion.question.id);
    this.activeQuestion.question.correct = correct;
    await this.singlePlayerService.waitFor(2000);
    const wasCorrect = this.activeQuestion.question.answer === correct;
    this.activeQuestion.state = wasCorrect ? 'answered' : 'failed';

    await this.singlePlayerService.waitFor(2000);


    if (wasCorrect) {
      const choices = ['move', 'points'];
      // randomize reward
      const _r1 = getNumberFromZeroToX(1);
      this.getReward(choices[_r1] as any);
    } else {
      const choices = ['go_back', 'remove_points'];
      const hasEnoughPoints = this.board.game.players[this.activeQuestion.playerUid].points >= this.activeQuestion.question.qPoints;

      if (hasEnoughPoints) {
        const _r1 = getNumberFromZeroToX(1);
        this.getReward(choices[_r1] as any);
      } else {
        this.getReward('go_back');
      }
    }
  }

  async getReward(rewardType: 'points' | 'move' | 'go_back' | 'remove_points'): Promise<void> {
    console.log(rewardType);
    const affectedUid = this.activeQuestion.playerUid;
    // set timeout to close
    switch (rewardType) {
      case 'move': {
        this.activeQuestion.state = 'finishedM';
        const stepsToMove = this.diffToStepsMap[this.activeQuestion.question.diff];
        for (let i = 0; i < stepsToMove; i++) {
          await this.singlePlayerService.waitFor(this.moveInterval);
          this.board.game.players[affectedUid].position++;
          this.audioService.playMoveSound();
        }
        break;
      }
      case 'go_back': {
        this.activeQuestion.state = 'failedM';
        for (let i = this.board.game.players[affectedUid].position; i > this.board.game.players[affectedUid].oldPosition; i--) {
          await new Promise(res => setTimeout(res, this.moveInterval));
          this.board.game.players[affectedUid].position -= 1;
          this.audioService.playMoveSound();
        }
        break;
      }
      case 'points': {
        this.activeQuestion.state = 'finishedP';
        this.board.game.players[affectedUid].points += this.activeQuestion.question.qPoints;
        break;
      }
      case 'remove_points': {
        this.activeQuestion.state = 'failedP';
        const oldPoints = this.board.game.players[affectedUid].points;
        if (oldPoints < this.activeQuestion.question.qPoints) {
          // not enough points
          console.error('Not enough points');
          break;
        } else {
          this.board.game.players[affectedUid].points -= this.activeQuestion.question.qPoints;
          break;
        }
      }
    }
    await this.singlePlayerService.waitFor(5000);
    this.activeQuestion = null;
    if (affectedUid !== 'bot') {
      await new Promise(res => setTimeout(res, 2000));
      this.rollDice('bot');
    } else {
      this.canRoll = true;
    }
  }

  async getHelp(help: 'help_50' | 'help_skip'): Promise<void> {
    console.log(help);

    switch (help) {
      case 'help_50': {
        this.board.game.players[this.user.uid].points -= HELPS.help_50;
        this.board.game.players[this.user.uid].helpUsed.help_50++;
        const newAnswers = halveAnswers(this.activeQuestion.question);
        this.activeQuestion.question.answers = newAnswers;
        break;
      }
      case 'help_skip': {
        this.board.game.players[this.user.uid].points -= HELPS.skip;
        this.board.game.players[this.user.uid].helpUsed.skip++;
        this.activeQuestion.state = 'skipped';
        await this.singlePlayerService.waitFor(5000);
        this.activeQuestion = null;
        this.rollDice('bot');
        break;
      }
    }
  }

  async answerQuestion(ans: string): Promise<void> {
    const correct = await this.questionService.getAnswerForQuestion(this.activeQuestion.question.id);
    this.activeQuestion.question.answer = ans;
    this.activeQuestion.question.correct = correct;
    if (ans === this.activeQuestion.question.correct) {
      this.activeQuestion.state = 'answered';
    } else {
      this.activeQuestion.state = 'failed';
    }
  }

  async qTurnFinished(): Promise<void> {
    await this.answerQuestion('');
  }

  quitGame(): void {
    // maybe reset
    location.reload();
  }

  async removeFiveSecondTimer(): Promise<void> {
    const uidAffected = this.activeGameEvent.playerUid;
    this.fiveSecondTimer = 100;
    this.activeGameEvent = null;
    this.isMyGameEvent = null;
    const gameEvent = this.board.game.gameEvent;


    const _newMoveInterval = gameEvent.id === 'gameEvent_CUSTOM' ? 100 : this.moveInterval;

    // do event action
    if (gameEvent.points) {
      this.board.game.players[uidAffected].points += (this.board.game.players[uidAffected].points + gameEvent.points < 0 ? -this.board.game.players[uidAffected].points : gameEvent.points);
    } else {
      const goBack = gameEvent.step < 0;
      if (!goBack) {
        for (let i = 0; i < gameEvent.step; i++) {
          await this.singlePlayerService.waitFor(_newMoveInterval);
          this.board.game.players[uidAffected].position++;
          this.audioService.playMoveSound();
          // check if reached the end
        }
      } else {
        for (let i = gameEvent.step; i < 0; i++) {
          await this.singlePlayerService.waitFor(_newMoveInterval);
          this.board.game.players[uidAffected].position--;
          this.audioService.playMoveSound();
        }
      }
    }


    // this.changeTurn();
    // roll dice
    console.log(this.board.game);



    const isBotTurn = this.board.game.turnIndex === 1;
    if (isBotTurn) {
      // roll for bot
      await this.singlePlayerService.waitFor(2000);
      this.rollDice('bot');
    } else {
      this.canRoll = true;
    }
  }

  changeTurn(): void {
    this.board.game.turnIndex = this.board.game.turnIndex === 0 ? 1 : 0;
  }
}

<div *ngIf="!started else showGame" class="elevated-card room p-3 w-50 mt-5 ml-auto mr-auto">
    <div class="d-flex flex-column w-50 m-auto">
        <h2 class="text-center">Το παιχνίδι σου</h2>

        <hr class="w-100">
        <div class="d-flex flex-column mb-2">
            <h3 class="mb-2">Μέγεθος παιχνιδού</h3>
            <mat-radio-group name="smallRadio" [(ngModel)]="newGame.isSmall">
                <mat-radio-button class="mr-2" [value]="true">Μικρό</mat-radio-button>
                <mat-radio-button [value]="false">Μεγάλο</mat-radio-button>
            </mat-radio-group>
        </div>
        <hr class="w-100">
        <mat-form-field appearance="fill">
            <mat-label>Πόντοι-Στόχος</mat-label>
            <input matInput required type="number" [(ngModel)]="newGame.minPoints" min="0">
        </mat-form-field>
        <hr class="w-100">
        <div class="d-flex flex-column">
            <h3>Μέγιστος αριθμός βοηθειών</h3>
            <mat-form-field appearance="fill">
                <mat-label>Βοήθεια 50/50</mat-label>
                <input matInput required type="number" [(ngModel)]="newGame.maxHelps.help_50" min="0">
            </mat-form-field>
            <mat-form-field appearance="fill">
                <mat-label>Βοήθεια πάσο</mat-label>
                <input matInput required type="number" [(ngModel)]="newGame.maxHelps.skip" min="0">
            </mat-form-field>
        </div>
        <div class="d-flex align-items-center justify-content-center">

            <button mat-raised-button class="create-btn" (click)="startGame()"> Παίξε </button>
        </div>
    </div>
</div>

<ng-template #showGame>

    <app-players-hud *ngIf="board?.game" [minPoints]="board.game.minPoints" [players]="board.game.players"
        [user]="user"></app-players-hud>
    <!-- <div *ngIf="board?.game" class="d-flex flex-column position-absolute hud">
        <div class="d-flex align-items-center w-100"
            *ngFor="let player of $any(board.game.players | keyvalue);trackBy: trackById"
            [style.textDecoration]="player.value.uid === user.uid ? 'underline' : ''">
            <span>{{player.value.displayName}} : {{player.value.points ? player.value.points : 0}}</span>
            <img class="ml-auto" [src]="'assets/heroes/'+player.value.hero.name+'.png'" width="25px" height="25px">
        </div>

    </div> -->

    <div *ngIf="board && board.game" class="game-window">
        <div class="board">
            <div *ngFor="let row of board.rows;let rowIndex = index;"
                class="g-row d-flex w-100 align-items-center justify-content-evenly">
                <div *ngFor="let cell of row.cells; let colIndex = index;" class="d-flex g-cell rounded"
                    [ngClass]="{'big': board.game.isSmall, 'small': !board.game.isSmall}">

                    <ng-container *ngTemplateOutlet="image; context: {index: cell.index}"></ng-container>

                    <div class="players-container">
                        <div *ngFor="let p of $any(board.game.players | keyvalue); trackBy: trackById" class="player">
                            <img *ngIf="p.value.position === cell.index" [alt]="p.value.name"
                                [src]="'assets/heroes/' +p.value.hero.name + '.png'" class="player-icon">
                        </div>
                    </div>
                </div>
            </div>

            <div *ngIf="canShowDiceAnimation" class="event-container">
                <app-dice [isSinglePlayer]="true" [game]="board.game" [noSound]="settings.effectsMute"
                    [diceResult]="diceResult" (changeSomething)="canShowDiceAnimation = false">
                </app-dice>
            </div>
        </div>
    </div>
    <div class="turnname-container">
        <span *ngIf="turnPlayer === user.displayName">Είναι η σειρά σου</span>
        <span *ngIf="turnPlayer === 'Υπολογιστής'">Είναι η σειρά του Υπολογιστή</span>
    </div>
    <div class="dice">
        <button class="die-btn" mat-icon-button [disabled]="!canRoll" (click)="rollDice(this.user.uid)">
            <mat-icon class="die-icon" svgIcon="die"></mat-icon>
        </button>
    </div>
    <app-question-modal *ngIf="activeQuestion" [game]="board.game" [question]="board.game.question" [user]="user"
        [canDoAction]="canDoAction" (getHelpEvent)="getHelp($event)" (getRewardEvent)="getReward($event)"
        (answeringQuestion)="answerQuestion($event)" (qTurnFinished)="qTurnFinished()" [IS_SINGLE]="true">

    </app-question-modal>


    <div *ngIf="gameOverPlayer" class="event-container">
        <h2>  {{gameOverPlayer === 'Υπολογιστής' ? 'Ο Υπολογιστής κέρδισε!' : 'Κέρδισες!'}}</h2>
        <button mat-raised-button (click)="quitGame()">Έξοδος</button>
    </div>

    <div *ngIf="activeGameEvent" class="event-container">
        <div class="text-center mb-3" style="font-size: 14pt;" *ngIf="!isMyGameEvent">
            Ο {{activeGameEvent.playerUid === 'bot' ? 'Υπολογιστής' : ' χρήστης '+board.game.players[activeGameEvent.playerUid].displayName}} έπεσε σε γεγονός
        </div>
        <h1 class="text-center mt-2">{{!isMyGameEvent ? '"'+activeGameEvent.text+'"' : activeGameEvent.text }}
        </h1>
        <div *ngIf="isMyGameEvent" class="w-75">
            <mat-progress-bar mode="determinate" [value]="fiveSecondTimer" style="height: 10px;">
            </mat-progress-bar>
        </div>
        <!-- <button *ngIf="isMyGameEvent" (click)="answerGameEvent()">Ok</button> -->
    </div>

    <div class="settings-container">
        <button mat-icon-button class="settings-btn" (click)="showSettings = !showSettings"
            [style.background]="showSettings ? '#3f99ec' : '#3f99ec80'">
            <mat-icon class="settings-icon" svgIcon="settings2"></mat-icon>
        </button>
    </div>

    <div *ngIf="showSettings" class="event-container">
        <h1 class="text-center mb-auto mt-3">Ρυθμίσεις</h1>

        <div class="d-flex flex-column w-75 mb-auto">
            <!-- MUSIC -->
            <h2 class="text-center">Μουσική</h2>
            <mat-slider [value]="settings.music * 100" (change)="turnVolume('music',$event.value)"></mat-slider>
            <!-- SOUND EFFECTS -->
            <h2 class="text-center">Ηχητικά εφέ</h2>
            <mat-slider [value]="settings.effects * 100" (change)="turnVolume('effects',$event.value)"></mat-slider>

            <mat-checkbox [checked]="settings.musicMute" (change)="setMute('musicMute', $event.checked)">Σίγαση μουσικής
            </mat-checkbox>
            <mat-checkbox [checked]="settings.effectsMute" (change)="setMute('effectsMute', $event.checked)">Σίγαση
                ηχητικών
                εφέ</mat-checkbox>
        </div>
    </div>



    <ng-template #image let-index="index">
        <div class="image" *ngIf="gameEventsMap[index] || gameQuestionsMap[index] else showIndex">
            <img [src]="gameEventsMap[index] ? './assets/ex.png' : gameQuestionsMap[index] ? './assets/q.png' : ''"
                alt="">
        </div>
        <ng-template #showIndex> {{index}} </ng-template>

    </ng-template>

</ng-template>
