// greek-mythos-angular-2/src/app/views/question-modal/question-modal.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { takeUntil } from 'rxjs/operators';
import { Game, GameQuestion } from '@app/models/game';
import { User } from '@app/models/user';
import { TimerService } from '@app/services/timer.service';
import { HELPS } from '@env/environment';

@Component({
  selector: 'app-question-modal',
  templateUrl: './question-modal.component.html',
  styleUrls: ['./question-modal.component.scss']
})
export class QuestionModalComponent implements OnInit {

  help = HELPS;

  diffToStepsMap = {
    'easy': `1 βήμα`,
    'medium': `2 βήματα`,
    'hard': `3 βήματα`,
  };

  @Input() IS_SINGLE = false;
  @Input({required: true}) question!: GameQuestion;
  @Input({required: true}) game!: Game;
  @Input({required: true}) user!: User;
  @Input({required: true}) canDoAction!: boolean;

  @Output() answeringQuestion = new EventEmitter();
  @Output() getHelpEvent = new EventEmitter();
  @Output() getRewardEvent = new EventEmitter();

  isMyQuestion = false;

  destroy = new EventEmitter();

  @Output() qTurnFinished = new EventEmitter();

  qTimer: number | null = 100;


  constructor(
    private timerService: TimerService,
  ) { }

  ngOnInit(): void {
    console.log(this.canDoAction);

    this.isMyQuestion = this.question.playerUid === this.user.uid;
    this.startQuestionTimer();
  }

  canGetHelp(help: 'help_50' | 'help_skip'): boolean {
    const maxHelps = help === 'help_50' ? this.game.maxHelps.help_50 : this.game.maxHelps.skip;
    const userHelps = help === 'help_50' ? this.game.players[this.user.uid].helpUsed.help_50 : this.game.players[this.user.uid].helpUsed.skip;
    const pointsNeeded = help === 'help_50' ? this.help.help_50 : this.help.skip;
    const userPoints = this.game.players[this.user.uid].points ?? 0;

    const hasEnoughHelps = userHelps < maxHelps;
    const hasEnoughPoints = userPoints >= pointsNeeded;

    return (this.isMyQuestion && this.canDoAction && hasEnoughPoints && hasEnoughHelps);
  }

  getHelp(ans: string): void {
    this.canDoAction = false;
    this.destroy.emit();
    this.qTimer = 100;
    if (ans === 'help_50') {
      this.startQuestionTimer();
    }
    this.getHelpEvent.emit(ans);
  }

  getReward(rewardType: 'points' | 'move' | 'go_back' | 'remove_points'): void {
    this.canDoAction = false;
    this.getRewardEvent.emit(rewardType);
  }

  answerQuestion(ans: string): void {
    this.canDoAction = this.IS_SINGLE ? true : false;
    this.destroy.emit();
    this.qTimer = null;
    this.answeringQuestion.emit(ans);
  }

  startQuestionTimer(): void {
    if ((this.isMyQuestion || this.IS_SINGLE) && this.question.state === 'waitingAns') {
      // start counter
      this.timerService.getQuestionTimer().pipe(takeUntil(this.destroy))
        .subscribe(v => {
          if (v === -999) {

            this.qTimer = null;
            this.destroy.emit();
            this.qTurnFinished.emit(true);
            return;
          }
          const rel = ((100 * v) / 150);
          this.qTimer = rel;
        });
    }
  }

}

<div class="question-container">

    <ng-container [ngSwitch]="question.state">
        <ng-template [ngSwitchCase]="'waitingAns'">
            <!-- <span class="question-text"> {{question.question.text}} </span> -->
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">
                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" mat-raised-button (click)="answerQuestion(question.question.answers[0])">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" mat-raised-button (click)="answerQuestion(question.question.answers[1])">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" mat-raised-button (click)="answerQuestion(question.question.answers[2])">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" mat-raised-button (click)="answerQuestion(question.question.answers[3])">
                        {{question.question.answers[3]}}
                    </button>
                </div>
                <!-- <button [disabled]="!isMyQuestion" *ngFor="let ans of question.question.answers"
                    (click)="answerQuestion(ans)" class="answer">
                    {{ans}} </button> -->
                <div class="d-flex flex-column align-items-center mt-1"
                    *ngIf="isMyQuestion && question.question.answers.length == 4">
                    <h1>Βοήθειες</h1>
                    <div class="d-flex w-100 justify-content-between">
                        <button mat-raised-button [disabled]="!canGetHelp('help_50')" (click)="getHelp('help_50')">50/50
                            <span style="color: #c12c2c;">(-{{help.help_50}} πόντους)</span> <br>
                            {{game.players[user.uid].helpUsed.help_50}} / {{game.maxHelps.help_50}}
                        </button>
                        <button mat-raised-button [disabled]="!canGetHelp('help_skip')"
                            (click)="getHelp('help_skip')">Πάσο
                            <span style="color: #c12c2c;">(-{{help.skip}} πόντους)</span> <br>
                            {{game.players[user.uid].helpUsed.skip}} / {{game.maxHelps.skip}}
                        </button>
                    </div>
                </div>
                <h1 *ngIf="question.question.answers.length !== 4" class="text-center mt-2" style="color: #3f99ec;">Χρησιμοποιήθηκε η βοήθεια 50/50</h1>
            </div>
            <div *ngIf="!isMyQuestion" class="p-4 mb-4" style="color: #3f99ec; font-size: 14pt;">
                Αναμένεται απάντηση απο {{IS_SINGLE ? 'τον Υπολογιστή' :  'τον '+game.players[game.question!.playerUid].displayName}}
            </div>
            <div *ngIf="qTimer && (isMyQuestion || IS_SINGLE)" class="w-75">
               <mat-progress-bar class="mb-3" mode="determinate" [value]="qTimer"></mat-progress-bar>
            </div>
        </ng-template>
        <ng-template [ngSwitchCase]="'answered'">

            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">
                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                    [ngClass]="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>
                <!-- <button [disabled]="true" *ngFor="let ans of question.question.answers" (click)="answerQuestion(ans)"
                    class="answer" [ngClass]="ans === question.question.answer ? 'correct' : ''">
                    {{ans}} </button> -->
                    <h1 *ngIf="isMyQuestion" class="text-center mt-1" style="color: green;">
                        Απάντησες σωστά
                    </h1>
                    <h1 *ngIf="!isMyQuestion" class="text-center mt-1" style="color: #3f99ec;">
                        Ο {{game.players[game.question!.playerUid].displayName}} απάντησε σωστά την ερώτηση,
                        αναμένεται επιλογή κίνησης
                    </h1>
                <div *ngIf="isMyQuestion" class="d-flex w-100 justify-content-between">
                    <button mat-raised-button [disabled]="!canDoAction " (click)="getReward('move')">Πάνε {{diffToStepsMap[question.question.diff]}} μπροστά</button>
                    <button mat-raised-button [disabled]="!canDoAction " (click)="getReward('points')">Πάρε
                        {{question.question.qPoints}}
                        πόντους</button>
                </div>
            </div>
        </ng-template>

        <ng-template [ngSwitchCase]="'failed'">
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">

                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                        [ngClass]="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>

                <!-- <button [disabled]="true" *ngFor="let ans of question.question.answers" (click)="answerQuestion(ans)"
                    class="answer"
                    [ngClass]="question.question.answer === ans ? 'wrong' : ans === question.question.correct ? 'correct' : ''">
                    {{ans}} </button> -->
                    <h1 class="text-center mt-2" *ngIf="isMyQuestion" style="color: #c12c2c;">Απάντησες λάθος</h1>
                    <h1 class="text-center mt-2" *ngIf="!isMyQuestion" style="color: #c12c2c;">
                        Ο {{game.players[game.question!.playerUid].displayName}} απάντησε λάθος
                    </h1>
                <div *ngIf="isMyQuestion" class="d-flex align-items-center justify-content-between w-100 mt-1">
                    <button mat-raised-button [disabled]="!canDoAction " (click)="getReward('go_back')">Πάνε πίσω </button>
                    <button mat-raised-button [disabled]="!canDoAction || (game.players[user.uid].points! < question.question.qPoints)"
                        (click)="getReward('remove_points')">- {{question.question.qPoints}}
                        πόντους</button>
                </div>
            </div>
        </ng-template>

        <ng-template [ngSwitchCase]="'skipped'">
            <h1 *ngIf="isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                Χρησιμοποίησες πάσο
            </h1>
            <h1 *ngIf="!isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                Ο {{game.players[game.question!.playerUid].displayName}} χρησιμοποίησε πάσο
            </h1>
        </ng-template>

        <ng-template [ngSwitchCase]="'finishedM'">
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">

                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                    [ngClass]="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>

                <!-- <button [disabled]="true" *ngFor="let ans of question.question.answers" (click)="answerQuestion(ans)"
                    class="answer" [ngClass]="ans === question.question.answer ? 'correct' : ''">
                    {{ans}} </button> -->

                <h1 *ngIf="isMyQuestion" class="text-center mt-2" style="color: green;">Πήγες {{diffToStepsMap[question.question.diff]}} μπροστά</h1>
                <h1 *ngIf="!isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Ο {{game.players[game.question!.playerUid].displayName}} πήγε {{diffToStepsMap[question.question.diff]}} μπροστά
                </h1>
            </div>
        </ng-template>

        <ng-template [ngSwitchCase]="'finishedP'">
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">

                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                    [ngClass]="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>

                <!-- <button [disabled]="true" *ngFor="let ans of question.question.answers" (click)="answerQuestion(ans)"
                    class="answer" [ngClass]="ans === question.question.answer ? 'correct' : ''">
                    {{ans}} </button> -->

                <h1 *ngIf="isMyQuestion" class="text-center mt-2" style="color: green;">Έλαβες {{question.question.qPoints}} πόντους</h1>
                <h1 *ngIf="!isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Ο {{game.players[game.question!.playerUid].displayName}} έλαβε {{question.question.qPoints}} πόντους
                </h1>
            </div>
        </ng-template>

        <ng-template [ngSwitchCase]="'failedM'">
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">
                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                        [ngClass]="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>
                <h1 *ngIf="isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Διάλεξες να πας πίσω
                </h1>
                <h1 *ngIf="!isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Ο {{game.players[game.question!.playerUid].displayName}} διάλεξε να πάει πίσω
                </h1>
            </div>
        </ng-template>

        <ng-template [ngSwitchCase]="'failedP'">
            <h1 class="text-center mt-2">{{ question.question.text }}</h1>
            <div class="d-flex flex-column p-4 w-100 mb-auto">
                <div class="d-flex justify-content-between mb-3">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[0])"
                    [ngClass]="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[0]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[1])"
                    [ngClass]="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[1]}}
                    </button>
                </div>
                <div *ngIf="question.question.answers.length === 4" class="d-flex justify-content-between">
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[2])"
                        [ngClass]="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[2]}}
                    </button>
                    <button [disabled]="true" mat-raised-button (click)="answerQuestion(question.question.answers[3])"
                    [ngClass]="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                        {{question.question.answers[3]}}
                    </button>
                </div>
                <h1 *ngIf="isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Έχασες {{question.question.qPoints}} πόντους
                </h1>
                <h1 *ngIf="!isMyQuestion" class="text-center mt-2" style="color: #3f99ec;">
                    Ο {{game.players[game.question!.playerUid].displayName}} έχασε {{question.question.qPoints}} πόντους
                </h1>
            </div>
        </ng-template>


    </ng-container>
</div>

// greek-mythos-vue/src/components/QuestionModal/QuestionModal.vue
<template>
    <div class="question-container">

    <template v-if="question.state === 'waitingAns'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-n tw-w-full tw-mb-auto">
            <div class="tw-flex tw-justify-between tw-mb-s">
                <button :disabled="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" @click="answerQuestion(question.question.answers[0])">
                    {{question.question.answers[0]}}
                </button>
                <button :disabled="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" @click="answerQuestion(question.question.answers[1])">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button :disabled="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" @click="answerQuestion(question.question.answers[2])">
                    {{question.question.answers[2]}}
                </button>
                <button :disabled="!isMyQuestion || !canDoAction || (question.question.answer !== undefined && question.question.answers.length === 4)" @click="answerQuestion(question.question.answers[3])">
                    {{question.question.answers[3]}}
                </button>
            </div>
            <div class="tw-flex tw-flex-col tw-items-center tw-mt-xs"
                v-if="isMyQuestion && question.question.answers.length == 4">
                <h1>Βοήθειες</h1>
                <div class="tw-flex tw-w-full tw-justify-between">
                    <button :disabled="!canGetHelp('help_50')" @click="getHelp('help_50')">50/50
                        <span style="color: #c12c2c;">(-{{HELPS.help_50}} πόντους)</span> <br>
                        {{game.player.helpUsed.help_50}} / {{game.maxHelps.help_50}}
                    </button>
                    <button :disabled="!canGetHelp('help_skip')"
                        @click="getHelp('help_skip')">Πάσο
                        <span style="color: #c12c2c;">(-{{HELPS.skip}} πόντους)</span> <br>
                        {{game.player.helpUsed.skip}} / {{game.maxHelps.skip}}
                    </button>
                </div>
            </div>
            <h1 v-if="question.question.answers.length !== 4" class="tw-text-center tw-mt-xs" style="color: #3f99ec;">Χρησιμοποιήθηκε η βοήθεια 50/50</h1>
        </div>
        <div v-if="!isMyQuestion" class="tw-p-s tw-mb-s" style="color: #3f99ec; font-size: 14pt;">
            Αναμένεται απάντηση απο {{IS_SINGLE ? 'τον Υπολογιστή' :  'τον '+game.player.displayName}}
        </div>
        <div v-if="qTimer && (isMyQuestion || IS_SINGLE)" class="tw-w-3/4">
            progress bar {{ qTimer }}
           <!-- <mat-progress-bar class="mb-3" mode="determinate" [value]="qTimer"></mat-progress-bar> -->
        </div>
    </template>
    <template v-else-if="question.state === 'answered'">

        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">
            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled
                :class="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled
                :class="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled
                :class="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled
                :class="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>
                <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-xs" style="color: green;">
                    Απάντησες σωστά
                </h1>
                <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                    Ο {{game.player.displayName}} απάντησε σωστά την ερώτηση,
                    αναμένεται επιλογή κίνησης
                </h1>
            <div v-if="isMyQuestion" class="tw-flex tw-w-full tw-justify-between">
                <button :disabled="!canDoAction " @click="getReward('move')">Πάνε {{diffToStepsMap[question.question.diff]}} μπροστά</button>
                <button :disabled="!canDoAction " @click="getReward('points')">Πάρε
                    {{question.question.qPoints}}
                    πόντους</button>
            </div>
        </div>
    </template>

    <template v-else-if="question.state === 'failed'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">

            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled @click="answerQuestion(question.question.answers[0])"
                :class="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[1])"
                :class="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled @click="answerQuestion(question.question.answers[2])"
                    :class="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[3])"
                :class="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>
                <h1 class="tw-text-center tw-mt-s" v-if="isMyQuestion" style="color: #c12c2c;">Απάντησες λάθος</h1>
                <h1 class="tw-text-center tw-mt-s" v-if="!isMyQuestion" style="color: #c12c2c;">
                    Ο {{game.player.displayName}} απάντησε λάθος
                </h1>
            <div v-if="isMyQuestion" class="tw-flex tw-items-center tw-justify-between tw-w-full tw-mt-xs">
                <button :disabled="!canDoAction " @click="getReward('go_back')">Πάνε πίσω </button>
                <button :disabled="!canDoAction || (game.player.points < question.question.qPoints)"
                    @click="getReward('remove_points')">- {{question.question.qPoints}}
                    πόντους</button>
            </div>
        </div>
    </template>

    <template v-else-if="question.state === 'skipped'">
        <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
            Χρησιμοποίησες πάσο
        </h1>
        <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
            Ο {{game.player.displayName}} χρησιμοποίησε πάσο
        </h1>
    </template>

    <template v-else-if="question.state === 'finishedM'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">

            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled @click="answerQuestion(question.question.answers[0])"
                :class="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[1])"
                :class="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled @click="answerQuestion(question.question.answers[2])"
                :class="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[3])"
                :class="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>

            <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-s" style="color: green;">Πήγες {{diffToStepsMap[question.question.diff]}} μπροστά</h1>
            <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Ο {{game.player.displayName}} πήγε {{diffToStepsMap[question.question.diff]}} μπροστά
            </h1>
        </div>
    </template>

    <template v-else-if="question.state === 'finishedP'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">

            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled @click="answerQuestion(question.question.answers[0])"
                :class="question.question.answers[0] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[1])"
                :class="question.question.answers[1] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled @click="answerQuestion(question.question.answers[2])"
                :class="question.question.answers[2] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[3])"
                :class="question.question.answers[3] === question.question.answer ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>

            <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-s" style="color: green;">Έλαβες {{question.question.qPoints}} πόντους</h1>
            <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Ο {{game.player.displayName}} έλαβε {{question.question.qPoints}} πόντους
            </h1>
        </div>
    </template>

    <template v-else-if="question.state === 'failedM'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">
            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled @click="answerQuestion(question.question.answers[0])"
                :class="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[1])"
                :class="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled @click="answerQuestion(question.question.answers[2])"
                    :class="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[3])"
                :class="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>
            <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Διάλεξες να πας πίσω
            </h1>
            <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Ο {{game.player.displayName}} διάλεξε να πάει πίσω
            </h1>
        </div>
    </template>

    <template v-else-if="question.state === 'failedP'">
        <h1 class="tw-text-center tw-mt-s">{{ question.question.text }}</h1>
        <div class="tw-flex tw-flex-col tw-p-s tw-w-full tw-mb-auto">
            <div class="tw-flex tw-justify-between tw-mb-s">
                <button disabled @click="answerQuestion(question.question.answers[0])"
                :class="question.question.answer === question.question.answers[0] ? 'wrong' : question.question.answers[0] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[0]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[1])"
                :class="question.question.answer === question.question.answers[1] ? 'wrong' : question.question.answers[1] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[1]}}
                </button>
            </div>
            <div v-if="question.question.answers.length === 4" class="tw-flex tw-justify-between">
                <button disabled @click="answerQuestion(question.question.answers[2])"
                    :class="question.question.answer === question.question.answers[2] ? 'wrong' : question.question.answers[2] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[2]}}
                </button>
                <button disabled @click="answerQuestion(question.question.answers[3])"
                :class="question.question.answer === question.question.answers[3] ? 'wrong' : question.question.answers[3] === question.question.correct ? 'correct' : ''">
                    {{question.question.answers[3]}}
                </button>
            </div>
            <h1 v-if="isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Έχασες {{question.question.qPoints}} πόντους
            </h1>
            <h1 v-if="!isMyQuestion" class="tw-text-center tw-mt-s" style="color: #3f99ec;">
                Ο {{game.player.displayName}} έχασε {{question.question.qPoints}} πόντους
            </h1>
        </div>
    </template>


</div>
</template>

<script setup lang="ts">
import { timer } from '@/services/timer.service';
import { onMounted, onUnmounted, ref } from 'vue';
import { HELPS } from '@/environment';

const emits = defineEmits([
  'answer',
  'getHelp',
  'getReward',
  'qTurnFinished',
]);
const props = defineProps({
    question: {
        type: Object,
        required: true,
    },
    isMyQuestion: {
        type: Boolean,
    },
    canDoAction: {
        type: Boolean,
    },
    IS_SINGLE: {
        type: Boolean,
    },
    game: {
        type: Object,
        required: true,
    },
    player: {
        type: Object,
        required: true,
        default: () => ({}),
    }
});
const diffToStepsMap: any = {
    'easy': `1 βήμα`,
    'medium': `2 βήματα`,
    'hard': `3 βήματα`,
};
const _timer = timer(0, 100, 150);
const qTimer = ref<number | null>(100);
const answerQuestion = (answer: string) => {
    _timer.reset();
    qTimer.value = null;
    emits('answer', answer);
}
const canGetHelp = (help: 'help_50' | 'help_skip') => {
    const player = props.player;
    const maxHelps = help === 'help_50' ? props.game.maxHelps.help_50 : props.game.maxHelps.skip;
    const userHelps = help === 'help_50' ? player.helpUsed.help_50 : player.helpUsed.skip;
    const pointsNeeded = HELPS[help as keyof typeof HELPS];
    const userPoints = player.points;

    const hasEnoughHelps = userHelps < maxHelps;
    const hasEnoughPoints = userPoints >= pointsNeeded;
 
    return (props.isMyQuestion && props.canDoAction && hasEnoughPoints && hasEnoughHelps);
};
const getHelp = (help: 'help_50' | 'help_skip') => {
    _timer.reset();
    qTimer.value = 100;
    if (help === 'help_50') {
        startQuestionTimer();
    }
    emits('getHelp', help);
}
const getReward = (rewardType: 'points' | 'move' | 'go_back' | 'remove_points') => emits('getReward', rewardType);

const startQuestionTimer = () => {
    if ((props.isMyQuestion || props.IS_SINGLE) && props.question.state === 'waitingAns') {
        _timer.subscribe(v => {
            if (v === -999) {
                emits('qTurnFinished');
                return;
            }
            const rel = ((100 * v) / 50);
            qTimer.value = rel;
        });
    }
}

onMounted(() => {
   startQuestionTimer();
});
onUnmounted(() => {
    _timer.stop();
});

</script>

<style scoped>
.question-container {
    width: 50%;
    position: absolute;
    z-index: 100;
    left: 25%;
    top: 25%;
    display: flex;
    flex-direction: column;
    align-items: center;
    background: #ffffffe8;
    right: 25%;
    bottom: 25%;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 5px;
    height: 600px;
}

h1 {
    word-break: break-word;
}


.question-text {
    font-size: 20pt;
    font-weight: 500;
    text-align: center;
    margin-top: 1rem;
}

button {
    width: 48%;
    outline: 0;
    white-space: pre-wrap !important;
    height: 100px;
}

.wrong { 
    background: red !important;
    color: black !important;
}

.correct {
    background: green !important;
    color: black !important;
}

.ball {
    background: blue;
    border-radius: 50%;
    width: 10px;
    height: 10px;
}
</style>
