// greek-mythos-angular/src/app/views/players-hud/players-hud.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Player, Players } from 'src/app/models/board';
import { User } from 'src/app/models/user';

@Component({
  selector: 'app-players-hud',
  templateUrl: './players-hud.component.html',
  styleUrls: ['./players-hud.component.scss']
})
export class PlayersHudComponent implements OnInit {

  @Input() players: Players;
  @Input() user: User;

  @Input() minPoints: number;

  expanded = false;

  constructor() { }

  ngOnInit(): void {
  }
  
  trackById(player) {
    return player.key;
  }

}

<div class="d-flex flex-column position-absolute hud" [style.width]="expanded ? '300px' : '100px'">
    <span>Στόχος: {{minPoints}}</span>
    <div class="mt-2 d-flex align-items-center w-100"
        *ngFor="let player of $any(players | keyvalue);trackBy: trackById"
        [style.textDecoration]="player.value.uid === user.uid ? 'underline' : ''">
        <img class="mr-2" [src]="'assets/heroes/'+player.value.hero.name+'.png'" width="25px" height="25px">
        <span *ngIf="expanded">{{player.value.displayName}} : {{player.value.points ? player.value.points : 0}}</span>
        <span *ngIf="!expanded"> {{player.value.points}} </span>
    </div>
    <button mat-icon-button>
        <mat-icon (click)="expanded = !expanded">{{expanded ? 'minimize' : 'open_in_full'}}</mat-icon>
    </button>
</div>

// greek-mythos-vue/src/pages/SinglePlayer/PlayersHud.vue
<template>
    <div class="tw-flex tw-flex-col tw-absolute hud" :class="{
        'tw-w-[300px]': expanded,
        'tw-w-[100px]': !expanded
    }">
    <span>Στόχος: {{minPoints}}</span>
    <div class="tw-mt-s tw-flex tw-items-center tw-w-full"
        v-for="player of players"
        :key="player.uid"
        :class="{
            'tw-underline': player.uid === user.uid,
        }">
        <img class="tw-mr-s" :src="'assets/heroes/'+player.hero.name+'.png'" width="25px" height="25px">
        <span v-if="expanded">{{player.displayName}} : {{player.points ? player.points : 0}}</span>
        <span v-esle> {{player.points}} </span>
    </div>
    <button @click="expanded = !expanded">
        <i>{{ expanded ? 'minimize' : 'open_in_full' }}</i>
    </button>
</div>
</template>
<script setup>
import { ref } from 'vue';
const expanded = ref(false);
defineProps({
    players: {
        type: Array,
        default: () => ({}),
    },
    minPoints: {
        type: Number,
        required: true,
        default: 0,
    },
    user: {
        type: Object,
        default: () => ({})
    }
})
</script>
